stages:
  ensure_16k_sr:
    cmd: python resample.py
    deps:
      - resample.py
      - wav_et_textgrids/FRcorp_textgrids_only/

  build_metadata:
    cmd: python build_dataframe.py
    deps:
      - build_dataframe.py
      - wav_et_textgrids/FRcorp_textgrids_only/
    outs:
      - rec_metadata.tsv

  get_representations:
    cmd: python get_rep.py
    deps:
      - get_rep.py
      - rec_metadata.tsv
    outs:
      - metadata.tsv
      - word_reps.pt

  convert_to_different_precisions:
    cmd: python convert.py
    deps:
      - convert.py
      - metadata.tsv
      - word_reps.pt
    outs:
      - reps_out/

  compute_distances:
    cmd: python compute_dist.py
    deps:
      - compute_dist.py
      - metadata.tsv
      - reps_out/
    outs:
      - dist_long.tsv
    metrics:
      - result.tsv

  make_plot:
    cmd: python plotting.py
    deps:
      - plotting.py
      - result.tsv
      - dist_long.tsv
    plots:
      - plots/dist.png
      - plots/time.png
      - plots/size.png
      - plots/dist_kde.png
      - plots/dist_hist.png